### ISSUE TITLE
inconsistent  contrastive training scheme with paper 

### ISSUE THREAD

**Issue by junho-jo** [KainingYing/CTVIS#15]
Hi, author!
I'm curious about the training scheme with contractive loss in your code.
In your paper, you said, 
#### "We use the MA embeddings of other instances in the memory bank as the major negative embeddings".
However, when i checked your source code, there was no code regarding the aforementioned statement.
Rather,  the code just samples the t-1 object queries as shown in below figure.

![image](https://github.com/KainingYing/CTVIS/assets/106468499/44563782-d137-4d4f-8ac8-55ba3fc0026d)

![image](https://github.com/KainingYing/CTVIS/assets/106468499/1bb75763-5723-4468-997a-0b2a33c94fa0)

Is there anything I missed?

**Comment by KainingYing** [comment]
Hi @junho-jo , this is a good question.

This is a mistake. When we cleaned the code, we checked out the wrong branch which was not the right branch when we submitted the papers. I will fix this problem ASAP. Thanks again for reminding this.

**Comment by junho-jo** [comment]
is there any plan to fix th branch?!
