### ISSUE TITLE
Register Custom Dataset

### ISSUE THREAD

**Issue by mbk2103** [KainingYing/CTVIS#18]
How to we register own dataset to CTVIS? Register(Colab tutorial) of Detectron2 is not working.
Page URL: https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html

**Comment by KainingYing** [comment]
Hi @mbk2103 ,

Thanks for your attention on our work.

Can you give more details about your dataset? Image dataset (MS COCO) or video dataset(YTVIS,OVIS)?

**Comment by mbk2103** [comment]
Thanks for your response.

Yes, my dataset is in the YTVIS format. It includes 132 frames in the training files, 29 frames in the validation files, and 28 frames in the test files. I have organized it according to the VITA data preparation format. Would you like me to explain the steps I followed to do this?

**Comment by KainingYing** [comment]
Hi @mbk2103 ,

Thank you for the details you provided. May I ask how many categories are in your dataset?

I showed how to define YTVIS19, you can also easily imitate for a custom dataset. There are several steps you need to do:

- You should define the categories in your dataset. Please refer to [THIS](https://github.com/KainingYing/CTVIS/blob/c1ed15cb11257f7f54646c23706404f95d165a5c/ctvis/data/vis/ytvis.py#L23) and [THIS](https://github.com/KainingYing/CTVIS/blob/c1ed15cb11257f7f54646c23706404f95d165a5c/ctvis/data/vis/ytvis.py#L142).
- Define the path to your image file and annotation file. Please refer to [THIS](https://github.com/KainingYing/CTVIS/blob/c1ed15cb112try57f7f54646c23706404f95d165a5c/ctvis/data/vis/builtin.py#L28).
- Define and invoke the registry function. Please refer to [THIS](https://github.com/KainingYing/CTVIS/blob/c1ed15cb11257f7f54646c23706404f95d165a5c/ctvis/data/vis/builtin.py#L78C1-L87C10) and [THIS](https://github.com/KainingYing/CTVIS/blob/c1ed15cb11257f7f54646c23706404f95d165a5c/ctvis/data/vis/builtin.py#L141).

**Comment by mbk2103** [comment]
Hi @KainingYing,

Thank you for your fast response.

I encountered an error when working with my custom dataset, which has only one class. The error is occurring at this [line](https://github.com/KainingYing/CTVIS/blob/c1ed15cb11257f7f54646c23706404f95d165a5c/ctvis/data/pseudo_video/rotate_coco_video_dataset_mapper.py#L285C35-L285C35), and I haven't changed any variable names.

In the file "CTVIS/ctvis/data/pseudo_video/rotate_coco_video_dataset_mapper.py," the error message is as follows:


CTVIS/ctvis/data/pseudo_video/rotate_coco_video_dataset_mapper.py", line 285, in __init__
] = self.tgt_metadata.thing_dataset_id_to_contiguous_id[v]
KeyError: 21

Can you please help me understand why this error is occurring and how to resolve it?

**Comment by KainingYing** [comment]
Hi @mbk2103 ,

Maybe you should modify the config file you run.

Specifically, you should overwrite the `DATASETS.TRAIN`, `DATASETS.TEST`, `DATASETS.DATASET_RATIO` and `MODEL.NUM_CLASSES`.

> In the file "CTVIS/ctvis/data/pseudo_video/rotate_coco_video_dataset_mapper.py," the error message is as follows:
CTVIS/ctvis/data/pseudo_video/rotate_coco_video_dataset_mapper.py", line 285, in init
] = self.tgt_metadata.thing_dataset_id_to_contiguous_id[v]
KeyError: 21

The error you mentioned above is caused by the error you implemented COCO joint training, I recommend you use Video training by setting `DATASETS.TRAIN` as your custom dataset only. 

BTW, considering your dataset is small, overfitting can happen easily, so I strongly recommend using our provided pre-trained models for fine-tuning.
