### ISSUE TITLE
A bug in your code

### ISSUE THREAD

**Issue by yuyuan2** [KainingYing/CTVIS#2]
Hi! Your work is excellent! 

I found a bug when running the following code "ython train_ctvis.py --num-gpus 4 --config-file configs/ytvis_2021/CTVIS_R50.yaml"

CTVIS/mask2former/modeling/matcher.py", line 111, in memory_efficient_forward
    cost_class = -out_prob[:, tgt_ids]
IndexError: tensors used as indices must be long, int, byte or bool tensors

Is that because of the environment? Thanks!

**Comment by KainingYing** [comment]
Thanks for your attention.

We fix this in the latest version.
