### ISSUE TITLE
Trying to test a model trained with 8 GPUs on a single GPU

### ISSUE THREAD

**Issue by mbk2103** [KainingYing/CTVIS#20]
Hi @KainingYing ,

I am attempting to test a model that was trained using 8 GPUs on a single GPU. I followed the instructions for the registration process as you explained, and I appreciate that. Could you please provide guidance on how to perform model training with a single GPU? 

Additionally, how can we modify the parameters that affect memory during the training of the model?

**Comment by KainingYing** [comment]
when training with a single GPU, you should decrease the `SOLVER.IMS_PER_BATCH`. At the same time, you should linearly scale the learning rate.

To save the memory, you should set the `INPUT.SAMPLING_FRAME_NUM` less than 10 (default). The smaller this parameter is, the fewer frames are sampled, and the less GPU memory is consumed.
