### ISSUE TITLE
IDOL experiments

### ISSUE THREAD

**Issue by mkimhi** [KainingYing/CTVIS#5]
Hi,

could you share or explain how you implemented Multi-Reference IDOL, as well as IDOL with Mask2Former?

thanks!

**Comment by KainingYing** [comment]
Thanks for your attention.

- **Multi-Reference IDOL** samples one key frame and multiple adjacent reference frames as the training sample. For each instance in key frames, we will select the corresponding positive and negative embeddings from all reference frames.
- **IDOL with Mask2Former** use the Mask2Former as the segementor. For reproducibility, we adopt a similar positive and negative sample assignment pattern as our CTVIS.

**Comment by mkimhi** [comment]
Thanks!
