### ISSUE TITLE
about contrastive learning on VPS

### ISSUE THREAD

**Issue by manli232111** [KainingYing/CTVIS#9]
Hi authors,

Your project is pretty good! I have a question about how do you perform Contrastive Learning on VPS, will you apply it for stuff queries? 

Thanks!

**Comment by KainingYing** [comment]
Hi @manli232111 

Thanks for your attention.

We perform Contrastive Learning on all types of queries (stuff and thing categories). Thanks to the Mask2Former's unified design for different queries, we can treat all queries the same way.
